baseURL = "https://hoovian.com"
languageCode = "en-us"
title = "scandi's blog"
theme = "PaperMod"

[params]
  defaultTheme = "auto"

[params.homeInfoParams]
  Title = "Hi there 👋"
  Content = "Welcome to my blog"

[[params.socialIcons]]
  name = "envelope"
  url = "mailto:scandi@hoovian.com"