baseURL = "https://scandihoovian.net"
languageCode = "en-us"
title = "scandi's blog"
theme = "PaperMod"

[params]
  defaultTheme = "auto"

[params.homeInfoParams]
  Title = "Hi there 👋"
  Content = "Welcome to my blog"
  Content = "Short intro text. <br><img src='/My Photos/bear.png' width='300'>"

[[params.socialIcons]]
  name = "envelope"
  url = "mailto:scandi@hoovian.com"